feat: add structure of my project
poznerrr/php_mvc pull request #1
Opened 2023-03-24 18:35 UTC by poznerrr

Попробовал разложить файлы. Подкючил composer. Проименовал namespaces согласно PSR-4.

Проблемы с удалением постов (отображаются как удаленные, затем появляются снова).

2023-03-24 19:33 UTC, texnicii commented on public/index.php
> +switch ($url)
можно поручить распределение в какой контроллер отправлять запрос, отдельному компоненту/классу "роутинг"

2023-03-24 19:42 UTC, texnicii commented on .idea/.gitignore
> +# Default ignored files
директорию .idea (и подобные служе,ные файлы IDE) обычно не коммитят т к они индивидуальны для каждого разработчика (а мы предполагаем, что с репозиторием всегда могут работать разные разработчики)

2023-03-24 19:45 UTC, texnicii commented on public/index.php
> +$indexController = new IndexController();
стоит обдумать вопрос: зачем инстанцировать объект контроллера который который может и не будет вызван (то есть как сделать так чтобы создавались только нужные в данном рантайме объекты)

2023-03-24 19:47 UTC, texnicii commented on vendor/autoload.php
> +<?php
vendor также обычно не коммитят в репозиторий потому что его содержимое может чуть отличаться от окружения в которым код будет запускаться (то есть, обычно vendor зависимости подтягиваются/выполняется composer install в момент сборки проекта для конкретного окружения)

2023-03-24 19:52 UTC, texnicii commented on controllers/IndexController.php
> +    public $posts;
надо типизировать свойства класса, так как практика показывает что строго типизированный код легче развивать и поддерживать

(и стоит заодно прочитать про включение строго режима strict_types)

2023-03-24 19:55 UTC, texnicii commented on models/PostService.php
> +    public function createPost($title, $text, $author)
также нужна и типизация аргументов (выше написал почему)

2023-03-24 20:06 UTC, texnicii commented on models/PostService.php
> +        $c->title = $title;
надо будет обсудить открытость/закрытость свойств класса (если в двух словах, свойства классов вполне могут быть публичными, но часто мы хотим лучше контролировать изменения состояния объектов тогда мы создаем методы аксессоры и мутаторы, а также чтобы реализовать единый интерфейс для подобных классов)

2023-03-24 20:12 UTC, texnicii commented on controllers/IndexController.php
> +        $this->posts =  $this->postService->getAllPosts();
стоит подумать как сделать так, чтобы метод render отвечал только за вывод сфомированных данных, а то сейчас нечеткая "граница" между контроллером и представлением, потому что метод рендер и инициирует получение данных и раскладывает их в представление

2023-03-24 20:14 UTC, texnicii commented on controllers/IndexController.php
> +        require dirname(__DIR__).'/views/index.phtml';
стоит посмотреть в сторону возможностей по управлению буферизации вывода (см. функции https://www.php.net/manual/en/function.ob-start и тд.)

2023-03-27 09:39 UTC, poznerrr commented on public/index.php
> +switch ($url)
создал отдельный класс RoutingController

2023-03-27 09:39 UTC, poznerrr commented on .idea/.gitignore
> +# Default ignored files
удалил директорию из гитхаба, добавил директорию в .gitignore

2023-03-27 09:42 UTC, poznerrr commented on public/index.php
> +$indexController = new IndexController();
исправил, теперь инстанцирую по необходимости (что-то вроде анонимного объекта)

2023-03-27 09:43 UTC, poznerrr commented on vendor/autoload.php
> +<?php
удалил директорию из гитхаба, добавил директорию в .gitignore

2023-03-27 09:44 UTC, poznerrr commented on models/PostService.php
> +        $c->title = $title;
добавил геттеры и сеттеры для свойств класса Post, определил значащее имя для объекта класса

2023-03-27 10:05 UTC, poznerrr commented on controllers/IndexController.php
> +        $this->posts =  $this->postService->getAllPosts();
создал отдельный класс для представления куда передаю данные из контроллера

2023-03-27 19:49 UTC, poznerrr commented on controllers/IndexController.php
> +    public $posts;
включил во все файлы strict_types=1, типизировал свойства класса

2023-03-27 19:50 UTC, poznerrr commented on models/PostService.php
> +    public function createPost($title, $text, $author)
типизировал аргументы и возвращаемые значения функций

2023-03-28 15:24 UTC, texnicii requested changes

2023-03-28 15:24 UTC, texnicii commented on controllers/RoutingController.php
> +<?php
класс роутинга не совсем контроллер, он либо часть контроллера, либо отдельный компонент.
Проще говоря: RoutingController у нас делает не тоже самое что IndexController (RoutingController - распределяет запрос по контроллерам, IndexController - исполняет/обрабатывает конкретный запрос), поэтому они не должны называться/располагаться по одному шаблону, стоит их как-то отделить друг от друга (создать поместить роутинг в другую директорию или придумать другое название)

2023-03-29 07:51 UTC, poznerrr commented on controllers/RoutingController.php
> +<?php
перенес в директорию app

2023-03-29 07:52 UTC, poznerrr commented on controllers/IndexController.php
> +        require dirname(__DIR__).'/views/index.phtml';
добавил методы ob_start()  и ob_end_flush(), на этом пока мои мысли - всё

2023-03-29 16:22 UTC, texnicii commented on controllers/IndexController.php
> +        require dirname(__DIR__).'/views/index.phtml';
увидел, только теперь возникло дублирование кода (вызовов ob_start()) и надо подумать как его избежать

2023-03-29 16:45 UTC, merged