Bootstrap + CRUD
poznerrr/php_mvc pull request #6
Opened 2023-04-25 07:04 UTC by poznerrr

Ещё немного причесал вёрстку (но до конца еще далеко).

Сделал пагинацию.

Добавил возможность проводить CRUD операции с постами, категориями, пользователями (практически весь функционал во вкладке admin panel, за исключением: добавить пость можно во вкладке Add News, добавить пользователя можно во вкладке Account -> Sign up).

2023-04-28 19:50 UTC, texnicii requested changes

2023-04-28 19:50 UTC, texnicii commented on public/scripts/categories/categories.js
> +function toggleEditModal(object) {
у bootstrap кстати есть готовы обработчик для toggle модалок
https://getbootstrap.com/docs/5.3/components/modal/

2023-04-28 19:50 UTC, texnicii commented on src/Controllers/Index.php
> +        $pageNumber =(int)($uriOptions['page'] ?? 1);
не очень хорошо передавать целый uriOptions если используется только $uriOptions['page']

2023-04-28 19:50 UTC, texnicii commented on src/App/Router.php
> +        method_exists($controller, $actionName) ? $controller->$actionName($uriOptions) :
как вариант поместить uriOptions в контроллер как свойство текущего контроллера,  так как uriOptions по сути это Request (некий объект с входящими параметрами запроса) который всегда один для одного экземпляра контроллера и более того, входящие параметры по сути конфигурируют контроллер (и тогда не нужно будет его пропихивать в render, он уже будет частью текущего контроллера)

еще можно взглянуть на то какой интерфейс предлагает php-fig для входящих запросов https://github.com/php-fig/http-message/blob/master/src/ServerRequestInterface.php

2023-04-28 19:50 UTC, texnicii commented on src/Controllers/Posts.php
> +            $this->postService->deletePost(($_POST['id']));
вряд ли render должен заниматься запуском удаления поста

2023-04-28 19:50 UTC, texnicii commented on src/Controllers/Posts.php
> +        $pageNumber = (int)($uriOptions['page'] ?? 1);
чтобы не делать каждый раз таких преобразований и проверок на существование, то как вариант можно сложить uriOptions (параметры запроса в класс) и тогда попытка достать что-то из них может выглядеть например, так $request->getInt('page', default: 1); или $request->get('page', default: 1);

2023-05-03 06:58 UTC, poznerrr commented on src/Controllers/Posts.php
> +            $this->postService->deletePost(($_POST['id']));
+

2023-05-06 18:19 UTC, merged