Single news + Authorization
poznerrr/php_mvc pull request #7
Opened 2023-04-28 18:23 UTC by poznerrr

1. Добавил возможность перехода на страницу новости.
2. Добавил регистрацию с паролем (миграция в бд), и авторизацию (пока только на уровне сессии, без куки).
3. Предыдущие замечения НЕ ИСПРАВЛЯЛ - не знаю в чём прикол, но у меня замечания, что ты показывал в среду не отображаются в комментариях. плюс вероятно ещё нагородил нечистого кода =(

02/05 - что успел добавить -  авторизацию на куки вместо сессий навесил, запускаю проект через докер

2023-04-28 19:40 UTC, texnicii commented on public/index.php
> +session_start();
в использовании сессий есть нюанс: сессия это считай файл на сервере, то есть много пользователей = много одновременно открытых файлов ан сервере = большая нагрузка. То есть, сессию стоит открывать тогда когда она действительно нужна, например когда пользователь аутентифицировался, а не для всех пользователей.

2023-04-28 20:36 UTC, texnicii requested changes

2023-04-28 20:36 UTC, texnicii commented on src/Controllers/Authorization.php
> +            $saltedPassword = md5($password . $desiredUser->getSalt());
вместо md5 лучше использовать https://www.php.net/manual/en/function.password-hash , так как md5 дает менее устойчивый к хэш + password-hash гибкая функция (можно выбирать алгоритмы хэширования)

дополнительная соль, вероятно повысит надежность, но только не для случаев когда кто-то получил доступ к базе (то есть имеет список уникальных строк соли для каждого пользователя) поэтому можно не заморачиваться с дополнительной солью при использовании password-hash, кмк

2023-04-28 20:36 UTC, texnicii commented on src/Controllers/Authorization.php
> +        unset($_SESSION['auth']);
```suggestion
        unset($_SESSION['auth'], $_SESSION['id'], $_SESSION['login']);

```

2023-04-28 20:36 UTC, texnicii commented on src/Controllers/Registration.php
> +            $saltedPassword = md5($_POST['user-password'] . $salt);
https://www.php.net/manual/en/function.password-hash

2023-04-28 20:36 UTC, texnicii commented on src/Layouts/authorization.phtml
> +                echo <<< _END
одновременно 3 способа вывода HTML в одном файле, стилистически лучше использовать какой-то один

2023-04-28 20:36 UTC, texnicii commented on src/Layouts/index.phtml
> +                echo "<div class='card-text'>" . mb_strimwidth( (strip_tags($post->getText(),['p','br'])), 0, 200, '...') . "</div>";
наверное тут случайно может так совпасть что обрежется HTML тэг (например, останется <p)

2023-04-28 20:36 UTC, texnicii commented on src/Layouts/news.phtml
> +            echo "<div class='card center-block p-3 my-2'>";
слишком много echo стилистически некрасиво выглядит, лучше просто HTML написать, тогда преемственность с другими шаблонизаторами будет (с twig например)

2023-04-28 20:36 UTC, texnicii commented on src/Models/User.php
> +    public function __construct(int|null $id = null, string|null $name = null, string|null $password = null, string|null $salt = null,)
```suggestion
    public function __construct(?int $id = null, ?string $name = null, ?string $password = null, ?string $salt = null,)

```

2023-04-28 20:36 UTC, texnicii commented on src/Models/User.php
>          if (isset($id)) {
если ты используешь null как значение по умолчанию, либо точно задана переменная, то лучше сравнивать более четко по типу вместо isset (например !==null)

2023-04-28 20:36 UTC, texnicii commented on src/Models/User.php
>          if (isset($name)) {
тут не совсем понятно, вроде у аргументов есть значения по умолчанию, поэтому как они могут быть не заданы (то есть зачем проверять на isset?) и что будет есть создастся объект "пользователь" без имени или пароля (и может такое быть вообще)?

2023-04-28 20:36 UTC, texnicii commented on src/Views/View.php
> +    protected bool|null $isAuth;
для типа bool, тем более isAuth не особо понятно зачем еще 3е состояние (null) - он либо аутентифицирован, либо нет
поэтому 
```suggestion
    protected bool $isAuth = false;

```

2023-04-28 20:36 UTC, texnicii commented on src/Models/User.php
> +    public function __construct(int|null $id = null, string|null $name = null, string|null $password = null, string|null $salt = null,)
тут можно property promotion применить https://php.watch/versions/8.0/constructor-property-promotion (то есть свойства описать прямо в конструторе, будет короче)

2023-04-28 20:36 UTC, texnicii commented on src/Views/View.php
> +    protected string|null $userLogin;
```suggestion
    protected ?string $userLogin;

```

2023-04-28 20:36 UTC, texnicii commented on src/Views/View.php
> +    protected int|null $userId;
```suggestion
    protected ?int $userId;

```

2023-04-28 20:36 UTC, texnicii commented on src/Views/View.php
> +        $this->isAuth = $_SESSION['auth']??null;
в сессии конечно можно закешировать дополнительные данные пользователя (логин и тд.), но тогда надо предусмотреть обновление данных в сессии, иначе если пользователь поменяет имя, то в сессии останется старое)

Или хранить в сессии что-то одно (например id) и доставать каждый раз актуальный объект пользователя из базы.

2023-04-28 20:36 UTC, texnicii commented on src/Controllers/Authorization.php
> +                $_SESSION['auth'] = true;
если/когда сессия на сервере кончится, то пользователь разлогинится сам того не желая, поэтому было бы хорошо хранить некоторые данные авторизации у пользователя (в браузере - в cookie)

2023-04-29 07:34 UTC, texnicii commented on src/Layouts/authorization.phtml
> +                echo '<div class="text-info">Вы успешно авторизованы</div>';
```suggestion
                ?>
                <div class="text-info">Вы успешно авторизованы</div>
                <?php

```

2023-05-02 11:29 UTC, poznerrr commented on src/Controllers/Authorization.php
> +        unset($_SESSION['auth']);
+

2023-05-02 11:46 UTC, poznerrr commented on src/Views/View.php
> +    protected int|null $userId;
+

2023-05-02 11:47 UTC, poznerrr commented on src/Views/View.php
> +    protected string|null $userLogin;
+

2023-05-02 11:48 UTC, poznerrr commented on src/Views/View.php
> +    protected bool|null $isAuth;
+

2023-05-02 12:01 UTC, poznerrr commented on src/Models/User.php
>          if (isset($name)) {
у меня пользователь без пароля создатется когда она является чатсью поста, я решил что пароль вытаскивать не обязательно для этого.. или неправильно?

2023-05-02 12:01 UTC, poznerrr commented on src/Models/User.php
>          if (isset($id)) {
+

2023-05-02 12:02 UTC, poznerrr commented on src/Models/User.php
> +    public function __construct(int|null $id = null, string|null $name = null, string|null $password = null, string|null $salt = null,)
+

2023-05-02 12:31 UTC, poznerrr commented on src/Controllers/Authorization.php
> +            $saltedPassword = md5($password . $desiredUser->getSalt());
изменил +

2023-05-02 12:32 UTC, poznerrr commented on src/Controllers/Registration.php
> +            $saltedPassword = md5($_POST['user-password'] . $salt);
+

2023-05-02 12:35 UTC, poznerrr commented on src/Models/User.php
> +    public function __construct(int|null $id = null, string|null $name = null, string|null $password = null, string|null $salt = null,)
+

2023-05-02 14:20 UTC, poznerrr commented on public/index.php
> +session_start();
теперь храню в куках

2023-05-02 14:21 UTC, poznerrr commented on src/Views/View.php
> +    protected bool|null $isAuth;
вообще удалил isAuth

2023-05-02 14:22 UTC, poznerrr commented on src/Views/View.php
> +        $this->isAuth = $_SESSION['auth']??null;
теперь храню id и password, login достаю из базы

2023-05-02 14:22 UTC, poznerrr commented on src/Controllers/Authorization.php
> +                $_SESSION['auth'] = true;
+ теперь хранится в куки

2023-05-03 09:14 UTC, poznerrr commented on src/Layouts/news.phtml
> +            echo "<div class='card center-block p-3 my-2'>";
+подправил

2023-05-03 09:14 UTC, poznerrr commented on src/Layouts/authorization.phtml
> +                echo <<< _END
исправил максимально на один способ

2023-05-03 09:15 UTC, poznerrr commented on src/Layouts/authorization.phtml
> +                echo '<div class="text-info">Вы успешно авторизованы</div>';
+

2023-05-03 15:39 UTC, texnicii commented on src/Models/User.php
>          if (isset($name)) {
смешивать заполнение базы контентом регистрацию "настоящих" пользователей как минимум не стоит, то есть не надо разрешать регистрироваться без пароля только потому что у нас где-то в другом месте мы создаем пользователей без пароля

2023-05-03 15:42 UTC, texnicii commented on docker/php/Dockerfile
> +&& rm -rf
`&& rm -rf` - это что-то лишне, непонятно что удаляется

2023-05-03 15:45 UTC, texnicii commented on docker/php/Dockerfile
> +COPY --from=composer /usr/bin/composer /usr/bin/composer
еще не хватает образа composer'а откуда копируется композер

2023-05-03 15:46 UTC, texnicii commented on src/App/AuthorizationChecker.php
> +
лишние пустые строки

2023-05-03 15:47 UTC, texnicii commented on src/App/AuthorizationChecker.php
> +        if (isset($_COOKIE['id']) && isset($_COOKIE['password'])) {
как вариант можно в один isset засунуть 2 или более переменных, раз у тебя && (твой вариант тоже норм)

2023-05-03 15:50 UTC, texnicii commented on src/Controllers/Categories.php
> +            header("Location: /?controller=Categories&action=renderDefault");
как вариант улучшения можно взглянуть на https://www.php.net/manual/en/function.http-build-query и/или сделать helper для генерации URL'ов сайта

2023-05-03 15:51 UTC, texnicii requested changes
немного замечаний по Dockerfile и предложения

2023-05-06 18:18 UTC, merged