Api
poznerrr/php_mvc pull request #9
Opened 2023-05-18 10:58 UTC by poznerrr

Добавил возможность совершать CRUD операции с новостями через http API при наличии jwt, который также можно получить авторизовавшись по api (примеры API запросов в tests/Postman)

UPD: 
разделил проверку валидности токена и создание dto
создал контейнер зависимостей

2023-05-19 08:20 UTC, texnicii requested changes

2023-05-19 08:20 UTC, texnicii commented on public/index.php
> +ini_set('display_errors', '0');
можно сделать зависимость уровня выводимых ошибок от переменной конфига, таким образом разделить продакшен мод от девелоп (в продакшен не стоит пользователю выводить ошибки, лучше их логировать)

2023-05-19 08:20 UTC, texnicii commented on config/config_example.php
> +$DtoFolder = "Source\\Models\\DTO";
а зачем, кстати, хранить пути?

2023-05-19 08:20 UTC, texnicii commented on src/App/JwtHandler.php
> +            'exp' => $expireAt,                           // Expire
лишние переменные особо не нужны
```suggestion
            'exp' => $date->modify('+10 minutes')->getTimestamp(),                           // Expire

```

2023-05-19 08:20 UTC, texnicii commented on src/App/JwtHandler.php
> +        {
тут что-то с форматированием

2023-05-19 08:20 UTC, texnicii commented on src/App/JwtHandler.php
> +        }
тут бы перенос строки

2023-05-19 08:20 UTC, texnicii commented on src/App/JwtHandler.php
> +        if (!$authorizedString || !preg_match('/Bearer\s(\S+)/', $authorizedString, $matches)) {
$authorizedString не bool, если ты хочешь проверить на null то лучше $authorizedString !==null , лишний каст к bool ни к чему

2023-05-19 08:20 UTC, texnicii commented on src/App/JwtHandler.php
> +        if (!$jwt) {
тут тоже $jwt не bool, лучше точное сравнение с учетом типа чтобы избежать ошибок после автоматического преобразования типов

2023-05-19 08:20 UTC, texnicii commented on src/App/Request.php
> +        $rawBody = file_get_contents('php://input');
обрати внимание на типы данных которые может вернуть file_get_contents,
то есть, лучше $rawBody !==false

2023-05-19 08:20 UTC, texnicii commented on src/App/Request.php
> +        $this->params = array_merge($uriParams, $_REQUEST, $_SERVER, $this->apiBody);
есть опасения что сложно потом будет разгадывать откуда взялось значение того или иного параметра если случайно пересекутся переменные в cookie и в json запросе

2023-05-19 08:20 UTC, texnicii commented on src/App/Router.php
> +        if (isset($parameters['method']) && $parameters['method'] === 'api') {
задумка понятна, но я не вижу особого смысла добавлять переменную method для разделения типа запросов, так как сам контроллер должен и так знать в каком виде ему готовить ответ и какие типы запросов он может принимать

2023-05-19 08:20 UTC, texnicii commented on src/App/Router.php
> +    private static function makeController(string $controllerName): Controller|ControllerAPI
тут надо будет разобраться почему тип у котроллеров разный. Вероятно, это как раз из-за заложенной в контроллеры недостаточной возможности расширяться

2023-05-19 08:20 UTC, texnicii commented on src/Controllers/NewsAPI.php
> +            list($isAuthorized, $authorizedMessage) = JwtHandler::checkJwt($incomeDto->authorizeString);
можно так

```suggestion
           [$isAuthorized, $authorizedMessage] = JwtHandler::checkJwt($incomeDto->authorizeString);

```

2023-05-19 08:20 UTC, texnicii commented on src/Controllers/NewsAPI.php
> +        if (!$incomeDto->isValid) {
у открытой переменной isValid есть минус, я могу сделать так $incomeDto->isValid = true и объект будет думать, что он валидный

тут можно подумать о принципе единственной обязанности/ответственности, то есть чтобы обязанность валидировать была не у самого Dto, а у дргугого компонента (который принимает Dto на вход и валидирует), а Dto занимался только сборкой данных в передаваемый объект

2023-05-19 08:20 UTC, texnicii commented on src/Interfaces/IAnswerDto.php
> +interface IAnswerDto
название смущает - не говорит разработчику что этот интрефейс предоставляет. Из набора методов понятно что ответ в виде json - поэтому можно и назвать JsonEncodableInterface или EncodableInterface

2023-05-19 08:20 UTC, texnicii commented on src/Models/DTO/AuthorizeDto.php
> +        public string $jwt)
что-то с форматирование

2023-05-19 08:20 UTC, texnicii commented on src/Models/DTO/GettingByIdDto.php
> +            $this->isValid = true;
думаю что валидация должна предполагать проверку обязательности передаваемых свойств и проверку типов (опционально)

вряд ли валидация данных в DTO зависит от авторизации

2023-05-19 08:20 UTC, texnicii commented on src/Models/DTO/NewsDto.php
> +                'answer' => $this->status,
было бы неплохо чтобы этот метод и подобные автоматически маппили поля объекта на ассоциативный массив, чтобы у разработчика не было возможности пропустить какой-то поле. тогда структура DTO максимально четко будет связано с данными которые выходят в виде json (+ можно будет сделать 1 общий метод для всех видом DTO)

2023-05-19 08:20 UTC, texnicii commented on src/Models/PostService.php
> +            $query = "SELECT posts.post_id, posts.title, posts.post_text, posts.post_date,
на форматированием запроса можно поработать, чтобы лучше читался

2023-05-22 10:53 UTC, poznerrr commented on src/App/JwtHandler.php
> +            'exp' => $expireAt,                           // Expire
+

2023-05-22 11:00 UTC, poznerrr commented on src/App/JwtHandler.php
> +        }
тут я не понял про перенос

2023-05-22 11:01 UTC, poznerrr commented on src/App/JwtHandler.php
> +        {
+

2023-05-22 11:07 UTC, poznerrr commented on src/App/JwtHandler.php
> +        if (!$authorizedString || !preg_match('/Bearer\s(\S+)/', $authorizedString, $matches)) {
+

2023-05-22 11:07 UTC, poznerrr commented on src/App/JwtHandler.php
> +        if (!$jwt) {
+

2023-05-22 13:15 UTC, poznerrr commented on src/Controllers/NewsAPI.php
> +            list($isAuthorized, $authorizedMessage) = JwtHandler::checkJwt($incomeDto->authorizeString);
+

2023-05-22 13:18 UTC, poznerrr commented on src/Controllers/NewsAPI.php
> +        if (!$incomeDto->isValid) {
я сделал так : смотрю request, если параметры соответсвуют тому Dto, который мы хотим создать, то инстанцирую dto, иначе отправляю сообщение, что параметры невалидны

2023-05-22 13:20 UTC, poznerrr commented on src/Models/DTO/AuthorizeDto.php
> +        public string $jwt)
+

2023-05-22 13:23 UTC, poznerrr commented on src/Models/DTO/GettingByIdDto.php
> +            $this->isValid = true;
+

2023-05-22 13:24 UTC, poznerrr commented on config/config_example.php
> +$DtoFolder = "Source\\Models\\DTO";
у меня нет ответа=) удалил)

2023-05-22 13:42 UTC, poznerrr commented on src/Interfaces/IAnswerDto.php
> +interface IAnswerDto
+

2023-05-22 13:47 UTC, poznerrr commented on src/App/Request.php
> +        $this->params = array_merge($uriParams, $_REQUEST, $_SERVER, $this->apiBody);
я как то изначально так и предположил, что ответственность будет возлагаться на разработчика по наименованию чтобы не пересеклись, а по архитектуре сейчас классу реквест и от него зависящим неважно откуда берутся значения

2023-05-24 07:07 UTC, texnicii commented on src/App/DtoValidator.php
> +            $prop_Name = $property->getName() ?? null;
кажется, что метод (в данном случае getName) какой-то результат всегда возвращает, поэтому дополнительно проверять существует то что он возвращает или нет - не нужно

?? - это по сути isset()

2023-05-24 07:07 UTC, texnicii commented on src/App/JwtHandler.php
> +        }
да просто так легче читать когда блоки кода, например блок if чуть отделен переносом от блоку try - чисто стилистический момент

2023-05-24 07:07 UTC, texnicii commented on src/App/Request.php
> +        $this->params = array_merge($uriParams, $_REQUEST, $_SERVER, $this->apiBody);
ок, так оставим, сейчас не критично. Но, для понимания, представь - когда в проект приходит новый разработчик (или просто прощло много времени) и никто уже не помнит какие переменные заданы в куках, какие параметры бывают в get запросах и требуется выбрать новую переменную - вероятность того что будет выбрано то что уже существует повышается, потому что никто не помнит и точно не знает где посмотреть (т к куки в одном месте задаются, роутинг URL в параметры в другом и тд.)

2023-05-24 16:33 UTC, texnicii commented on src/Controllers/NewsAPI.php
> +            exit();
```suggestion
            return;

```

2023-06-07 19:31 UTC, merged